from . import hr_employee
from . import hr_empl_relatives
from . import hr_empl_education
from . import hr_insurance
from . import hr_employee_public
from . import hr_work_process
from . import hr_contract
from . import res_company
from . import res_config_settings
from . import ir_ui_menu
from . import hr_department
from . import hr_ethnicity_religion
